default_platform(:android)

platform :android do

  desc "Build signed release AAB"
  lane :build_release do
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file"     => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias"      => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password"   => ENV["KEY_PASSWORD"],
      }
    )
  end

  desc "Upload signed AAB to Play Store"
  lane :upload_release do |options|
    supply(
      track:            options[:track] || ENV["SUPPLY_TRACK"] || "internal",
      aab:              ENV["SUPPLY_AAB"],
      package_name:     ENV["SUPPLY_PACKAGE_NAME"] || ENV["ANDROID_PACKAGE_NAME"],
      json_key:         ENV["SUPPLY_JSON_KEY"],
      skip_upload_apk:  true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
